# Generated by Django 3.0.5 on 2020-07-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('mail', models.CharField(max_length=60)),
                ('telefono', models.IntegerField()),
                ('mensaje', models.CharField(max_length=600)),
            ],
        ),
    ]
